server:
  port: 8081

spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: dr260420003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: c3VwZXJfc2VjcmV0X2tleV9tdXN0X2JlXzMyX2J5dGVzIQ==
  expiration: 900000         # 15
  refresh-expiration: 604800000  # 7
  prefix: "refresh:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka